export const MENU: Record<string, any[]> = {
  "HOT BEVERAGES": [{ item: "CAPPUCCINO", prices: { M: 65, L: 75 } }, { item: "CAFFE LATTE", prices: { M: 65, L: 75 } }, { item: "AMERICANO", prices: { M: 55, L: 60 } }, { item: "MOCHA", prices: { M: 75, L: 85 } }, { item: "CARAMEL MACCHIATO", prices: { M: 75, L: 85 } }, { item: "HOT CHOCOLATE", prices: { M: 65 } }, { item: "ESPRESSO", prices: { S: 35, D: 45 } }, { item: "FLAT WHITE", price: 80 }, { item: "TURKISH COFFEE", prices: { S: 35, D: 45 } }, { item: "REGULAR TEA", price: 30 }, { item: "FLAVOURED TEA", price: 30 }],
  "ICE BEVERAGES": [{ item: "ICE CAPPUCCINO", price: 75 }, { item: "ICE CAFFE LATTE", price: 75 }, { item: "ICE AMERICANO", price: 65 }, { item: "ICE MOCHA", price: 85 }, { item: "ICE CARAMEL MACCHIATO", price: 75 }, { item: "ICE CHOCOLATE", price: 75 }],
  "FRAPPE": [{ item: "ESPRESSO FRAPPE", price: 80 }, { item: "CARAMEL ESPRESSO FRAPPE", price: 85 }, { item: "MOCHA FRAPPE", price: 85 }, { item: "COOKIES CARAMEL FRAPPE", price: 100 }, { item: "PISTACHIO FRAPPE", price: 95 }, { item: "LOTUS FRAPPE", price: 75 }, { item: "KINDER FRAPPE", price: 80 }, { item: "STRAWBERRY FRAPPE", price: 75 }],
  "MILKSHAKE": [{ item: "VANILLA MILKSHAKE", price: 85 }, { item: "CARAMEL MILKSHAKE", price: 85 }, { item: "CHOCOLATE MILKSHAKE", price: 85 }, { item: "PISTACHIO MILKSHAKE", price: 100 }, { item: "KINDER MILKSHAKE", price: 90 }, { item: "OREO MILKSHAKE", price: 85 }, { item: "LOTUS MILKSHAKE", price: 85 }],
  "SMOOTHIE": [{ item: "MANGO SMOOTHIE", price: 65 }, { item: "STRAWBERRY SMOOTHIE", price: 65 }, { item: "LEMON MINT SMOOTHIE", price: 65 }, { item: "BLUEBERRY SMOOTHIE", price: 65 }, { item: "TROPICAL SMOOTHIE", price: 65 }],
  "BOBA": [{ item: "BOBA TEA", price: 80 }, { item: "BOBA BLUEBERRY", price: 75 }, { item: "BOBA MATCHA", price: 75 }, { item: "BOBA OREO", price: 80 }, { item: "BOBA STRAWBERRY", price: 75 }],
  "MATCHA": [{ item: "MATCHA", price: 50 }, { item: "MATCHA LATTE", price: 65 }, { item: "MATCHA STRAWBERRY", price: 55 }, { item: "MATCHA MANGO", price: 55 }, { item: "MATCHA COCONUT", price: 55 }],
  "MOJITO": [{ item: "MOJITO CLASSIC", price: 65 }, { item: "MOJITO BLUEBERRY", price: 65 }, { item: "MOJITO PASSION FRUIT", price: 75 }, { item: "MOJITO STRAWBERRY", price: 65 }],
  "PROTEIN SHAKE": [{ item: "CHOCOLATE BANANA SHAKE", price: 95 }, { item: "CHOCOLATE PEANUT BUTTER SHAKE", price: 100 }, { item: "CHOCOLATE COFFEE SHAKE", price: 100 }],
  "WAFFLE": [{ item: "CHOCOLATE WAFFLE", price: 85 }, { item: "CARAMEL WAFFLE", price: 85 }, { item: "PISTACHIO WAFFLE", price: 120 }, { item: "LOTUS WAFFLE", price: 85 }, { item: "KINDER WAFFLE", price: 90 }],
  "PANCAKE": [{ item: "CHOCOLATE PANCAKE", price: 75 }, { item: "CARAMEL PANCAKE", price: 75 }, { item: "PISTACHIO PANCAKE", price: 100 }, { item: "LOTUS PANCAKE", price: 75 }],
  "CROISSANT": [{ item: "PLAIN CROISSANT", price: 60 }, { item: "CHEESE CROISSANT", price: 95 }, { item: "TURKEY CROISSANT", price: 85 }, { item: "PISTACHIO CROISSANT", price: 120 }, { item: "NUTELLA CROISSANT", price: 80 }],
  "SANDWICH": [{ item: "TURKEY WRAP", price: 85 }, { item: "BEEF WRAP", price: 95 }, { item: "CHICKEN WRAP", price: 85 }, { item: "CLUB SANDWICH", price: 95 }, { item: "TUNA SANDWICH", price: 85 }],
  "SOFT DRINK": [{ item: "RED BULL", price: 65 }, { item: "MANGO JUICE", price: 50 }, { item: "ORANGE JUICE", price: 50 }, { item: "SMALL WATER", price: 10 }]
};

export const FULL_MENU: Record<string, any[]> = {
  "HOT BEVERAGES": [{ item: "CAPPUCCINO", prices: { M: 65, L: 75 } }, { item: "CAFFE LATTE", prices: { M: 65, L: 75 } }, { item: "CAFFE LATTE SPANISH", prices: { M: 65, L: 90 } }, { item: "CINNAMON LATTE", prices: { M: 65, L: 75 } }, { item: "AMERICANO", prices: { M: 55, L: 60 } }, { item: "MOCHA", prices: { M: 75, L: 85 } }, { item: "WHITE CHOCOLATE MOCHA", prices: { M: 75, L: 85 } }, { item: "CARAMEL MACCHIATO", prices: { M: 75, L: 85 } }, { item: "HOT CHOCOLATE", prices: { M: 65 } }, { item: "ESPRESSO", prices: { S: 35, D: 45 } }, { item: "RISTRETTO", prices: { S: 40, D: 45 } }, { item: "ESPRESSO MACCHIATO", prices: { S: 45, D: 50 } }, { item: "TURKISH COFFEE", prices: { S: 35, D: 45 } }, { item: "FRENCH COFFEE", price: 50 }, { item: "HAZELNUT COFFEE", price: 50 }, { item: "FLAT WHITE", price: 80 }, { item: "HOT LOTUS", price: 60 }, { item: "REGULAR TEA", price: 30 }, { item: "FLAVOURED TEA", price: 30 }, { item: "HERBS", price: 30 }],
  "ICE BEVERAGES": [{ item: "ICE CAPPUCCINO", price: 75 }, { item: "ICE CAFFE LATTE", price: 75 }, { item: "ICE LATTE SPANISH", price: 80 }, { item: "ICE LATTE SPANISH SAUCE", price: 90 }, { item: "ICE AMERICANO", price: 65 }, { item: "ICE MOCHA", price: 85 }, { item: "ICE WHITE CHOCOLATE MOCHA", price: 85 }, { item: "ICE CHOCOLATE", price: 75 }, { item: "ICE CARAMEL MACCHIATO", price: 75 }],
  "FRAPPE": [{ item: "ESPRESSO FRAPPE", price: 80 }, { item: "CARAMEL ESPRESSO FRAPPE", price: 85 }, { item: "MOCHA FRAPPE", price: 85 }, { item: "WHITE CHOCOLATE MOCHA FRAPPE", price: 85 }, { item: "COOKIES CARAMEL FRAPPE", price: 100 }, { item: "VANILLA FRAPPE", price: 70 }, { item: "CARAMEL FRAPPE", price: 70 }, { item: "CHOCOLATE FRAPPE", price: 70 }, { item: "PISTACHIO FRAPPE", price: 95 }, { item: "LOTUS FRAPPE", price: 75 }, { item: "KINDER FRAPPE", price: 80 }, { item: "STRAWBERRY FRAPPE", price: 75 }],
  "MILKSHAKE": [{ item: "VANILLA MILKSHAKE", price: 85 }, { item: "CARAMEL MILKSHAKE", price: 85 }, { item: "CHOCOLATE MILKSHAKE", price: 85 }, { item: "MANGO MILKSHAKE", price: 85 }, { item: "STRAWBERRY MILKSHAKE", price: 85 }, { item: "BLUEBERRY MILKSHAKE", price: 85 }, { item: "OREO MILKSHAKE", price: 85 }, { item: "LOTUS MILKSHAKE", price: 85 }, { item: "PISTACHIO MILKSHAKE", price: 100 }, { item: "KINDER MILKSHAKE", price: 90 }, { item: "NUTELLA MILKSHAKE", price: 85 }, { item: "COFFEE MILKSHAKE", price: 85 }],
  "SMOOTHIE": [{ item: "MANGO SMOOTHIE", price: 65 }, { item: "MANGO PASSION SMOOTHIE", price: 75 }, { item: "STRAWBERRY SMOOTHIE", price: 65 }, { item: "PEACH SMOOTHIE", price: 65 }, { item: "LEMON MINT SMOOTHIE", price: 65 }, { item: "BLUEBERRY SMOOTHIE", price: 65 }, { item: "WATERMELON SMOOTHIE", price: 65 }, { item: "KIWI SMOOTHIE", price: 65 }, { item: "TROPICAL SMOOTHIE", price: 65 }],
  "BOBA": [{ item: "BOBA TEA", price: 80 }, { item: "BOBA BLUEBERRY", price: 75 }, { item: "BOBA STRAWBERRY", price: 75 }, { item: "BOBA OREO", price: 80 }, { item: "BOBA MATCHA", price: 75 }],
  "MATCHA": [{ item: "MATCHA", price: 50 }, { item: "MATCHA STRAWBERRY", price: 55 }, { item: "MATCHA MANGO", price: 55 }, { item: "MATCHA COCONUT", price: 55 }, { item: "MATCHA LATTE", price: 65 }],
  "MOJITO": [{ item: "MOJITO CLASSIC", price: 65 }, { item: "MOJITO RED BULL", price: 70 }, { item: "MOJITO BLUEBERRY", price: 65 }, { item: "MOJITO PASSION FRUIT", price: 75 }, { item: "MOJITO KIWI", price: 65 }, { item: "MOJITO PEACH", price: 65 }, { item: "MOJITO STRAWBERRY", price: 65 }],
  "PROTEIN SHAKE": [{ item: "CHOCOLATE BANANA SHAKE", price: 95 }, { item: "CHOCOLATE PEANUT BUTTER SHAKE", price: 100 }, { item: "CHOCOLATE COFFEE SHAKE", price: 100 }, { item: "CHOCOLATE COCONUT SHAKE", price: 95 }],
  "WAFFLE": [{ item: "CHOCOLATE WAFFLE", price: 85 }, { item: "CARAMEL WAFFLE", price: 85 }, { item: "LOTUS WAFFLE", price: 85 }, { item: "PISTACHIO WAFFLE", price: 120 }, { item: "NUTELLA WAFFLE", price: 85 }, { item: "KINDER WAFFLE", price: 90 }, { item: "FOUR SEASON WAFFLE", price: 100 }],
  "PANCAKE": [{ item: "CHOCOLATE PANCAKE", price: 75 }, { item: "CARAMEL PANCAKE", price: 75 }, { item: "NUTELLA PANCAKE", price: 75 }, { item: "PISTACHIO PANCAKE", price: 100 }, { item: "LOTUS PANCAKE", price: 75 }, { item: "KINDER PANCAKE", price: 90 }],
  "CROISSANT": [{ item: "PLAIN CROISSANT", price: 60 }, { item: "CHEESE CROISSANT", price: 95 }, { item: "TRIPLE CHEESE CROISSANT", price: 85 }, { item: "TURKEY CROISSANT", price: 85 }, { item: "BEEF CROISSANT", price: 80 }, { item: "NUTELLA CROISSANT", price: 80 }, { item: "LOTUS CROISSANT", price: 80 }, { item: "PISTACHIO CROISSANT", price: 120 }, { item: "CHOCOLATE CROISSANT", price: 80 }, { item: "CARAMEL CROISSANT", price: 80 }, { item: "STRAWBERRY CROISSANT", price: 80 }],
  "SANDWICH": [{ item: "TURKEY WRAP", price: 85 }, { item: "BEEF WRAP", price: 95 }, { item: "CHICKEN WRAP", price: 85 }, { item: "CURRY SANDWICH", price: 95 }, { item: "BEEF SANDWICH", price: 85 }, { item: "TURKEY SANDWICH", price: 80 }, { item: "TUNA SANDWICH", price: 85 }, { item: "TANDOORI SANDWICH", price: 85 }, { item: "BARBECUE SANDWICH", price: 85 }, { item: "CLUB SANDWICH", price: 95 }, { item: "TRIPLE CHEESE SANDWICH", price: 95 }],
  "SOFT DRINK": [{ item: "SMALL WATER", price: 10 }, { item: "MOUSY", price: 45 }, { item: "RED BULL", price: 65 }, { item: "MANGO JUICE", price: 50 }, { item: "ORANGE JUICE", price: 50 }, { item: "STRAWBERRY JUICE", price: 50 }, { item: "GUAVA JUICE", price: 50 }],
  "ADDITION": [{ item: "SAUCE (CHOCOLATE - CARAMEL - STRAWBERRY - NUTELLA - LOTUS)", price: 20 }, { item: "SAUCE (PISTACHIO - KINDER)", price: 40 }, { item: "ESPRESSO", price: 30 }, { item: "BOBA", price: 35 }, { item: "TOPPING", price: 20 }, { item: "FLAVOR", price: 20 }, { item: "WHIPPED CREAM", price: 10 }, { item: "ICE CREAM", price: 15 }, { item: "MILK", price: 15 }]
};

export const SYS = `أنت AI Server ذكي لمقهى Double Zero. ردودك مختصرة وودودة بالعامية المصرية الطبيعية ممزوجة بالإنجليزي. لا تتجاوز 3-4 جمل أو bullet points. ركز بس على المنيو والخدمات. لو مش عارف تساعد، قول للعميل يكلم الكاشير.

BRAND: Double Zero | SLOGAN: "Everything's better when it's Double"
MENU: ${JSON.stringify(FULL_MENU)}`;

export const WELCOME = "أهلاً بيك في Double Zero ☕\nمزاجك رايح لسويت، سترونج، ولا حاجة منعشة؟\n\nWelcome to Double Zero! Sweet, strong, or refreshing — what's your mood?";
